server:
  port: 2001

spring:
  application:
    name: redis_data_service
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.0.99:26379, 192.168.0.99:16379
    database: 3
    #password:
    timeout: 3000


eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.99:8888/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.99
    instance-id: ${eureka.instance.ip-address}:${server.port}


logging:
  file:
    path: /log
    name: Redis_data.log
  level:
    com:
      example:
        DEBUG


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: *

